config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'admin' => 'homes#top'
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:index, :show, :update]
    resources :order_details, only:[:update]
    resources :genres, only:[:create, :index, :edit, :update]
    resources :items, only:[:new, :create, :index, :show, :edit, :update, :destroy]
  end

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    resources :addresses, only:[:create, :index, :edit, :update, :destroy]
    resources :orders, only:[:new, :create, :index, :show] do
      collection do
        post 'confirm'
      end
      member do
        get 'complete'
      end
    end
    resources :items, only:[:index, :show]
    resources :cart_items, only:[:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    resource :customers, only:[:show] do
      collection do
        get 'unsbscribe'
        patch 'withdraw'
      end
    end
  end

  devise_for :customers, skip:[:passwords], controllers:{
    registrations: "customers/registrations",
    sessions: "customers/sessions"
  }
  devise_for :admins, skip:[:registrations, :passwords], controllers:{
    sessions: "admins/sessions"
  }
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :genre_maps, dependent: :destroy, foreign_key: 'item_id'
  has_many :genres, through: :genre_maps
  has_many :cart_items, dependent: :destroy
  has_many :order_details

  validates :name, presence: true
  validates :price, presence: true

  has_one_attached :image

  def save_genres(sent_genres)
    current_genres = self.genres.pluck(:name) unless self.genres.nil?
    old_genres = current_genres - sent_genres
    new_genres = sent_genres - current_genres

    old_genres.each do |old|
      self.genres.delete Genre.find_by(name: old)
    end

    new_genres.each do |new|
      new_genre_map = Genre.find_or_create_by(name: new)
      self.genres << new_genre_map
    end
  end


  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def get_tax_include_price
    tax = 10
    add_tax = 1 + tax.to_f / 100
    (self.price.to_f * add_tax).round
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::ApplicationController

  def new
    @item = Item.new
  end

  def index
    @items = Item.all
  end

  def create
    @item = Item.new(item_params)
    genre_list = params[:item][:genre].split(',')
    if @item.save
      @item.save_genres(genre_list)
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end

  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    genre_list = params[:item][:genre].split(',')
    if @item.update(item_params)
      @item.save_genres(genre_list)
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to admin_items_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :genre_id, :introduction, :price, :is_active, :image)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
 <div class="col-md-7 col-lg-8">
 <h2>商品編集</h2>
   <%= form_with model:@item, :url => {:action => :update} do |f| %>
   <div class="form-group">
    <label for="items_imege">商品画像</label>
    <%= f.file_field :image %>
   </div>

   <div class="form-group">
    <label for="items_name">商品名</label>
    <%= f.text_field :name,class:"form-control" %>
   </div>

   <div class="form-group">
    <label for="items_introduction">商品説明</label>
    <%= f.text_field :introduction ,class:"form-control"%>
   </div>

   <div class="form-group">
    <label for="items_genre_id">ジャンル</label>
    <%= f.text_field :genre,class:"form-control" %>
   </div>

   <div class="form-group">
    <label for="items_price">税抜価格</label>
    <%= f.number_field :price,class:"form-control" %>
   </div>

   <div class="form-group">
    <label for="items_is_active">販売ステータス</label>
    <%= f.radio_button :is_active, true %>
    <%= f.label :is_active, "販売中" %>
    <%= f.radio_button :is_active, false %>
    <%= f.label :is_active, "販売停止中" %>
   </div>
　
　<div class="actions col-8">
   <%= f.submit '変更を保存',class:"btn btn-sm btn-success"%>
　</div>
　
  <% end %>
 </div>
</div>

app/views/admin/items/index.html.erb
<div class = "container">
 <div class ="row">
  <div class="col-md-10">
   <h4>商品一覧</h4>
  </div>

   <div class="col-md-2 ms-auto">
  	 <%= link_to new_admin_item_path do %>
  		 <span>新規商品登録</span>
  	 <% end %>
   </div>
 </div><br>

 <div class ="row">
  <table class = "table table-borderless">
   <thead class="table-active">
    <th>商品ID</th>
    <th>商品名</th>
    <th>税抜価格</th>
    <th>ジャンル</th>
    <th>ステータス</th>
   </thead>
   <% @items.each do |item| %>
   <tbody>
    <td><%= item.id %></td>
    <td><%=link_to item.name, admin_item_path(item.id) %></td>
    <td><%= item.price %></td>
    <td>
     <% item.genres.each do |genre| %>
      <%= genre.name %>
     <% end %>
    </td>
    <td>
     <% if item.is_active %>
        <span class="text-success">販売中</span>
       <% else %>
        <span class="text-secondary">販売停止中</span>
       <% end %>
    </td>
   </tbody>
   <% end %>
  </table>
 </div>
</div>

app/views/admin/items/new.html.erb
<div class= "container">
 <div class="col-md-7 col-lg-8">
 <h4>商品新規登録</h4>
   <%= form_with model:@item, :url => {:action => :create} do |f| %>
    
    <div class="form-group">
     <label for="items_imege">商品画像</label>
     <div class="col-auto">
      <%= f.file_field :image %>
     </div>
    </div>
    

    <div class="form-group">
     <label for="items_name">商品名</label>
     <div class="col-auto">
      <%= f.text_field :name,class:"form-control" %>
     </div>
    </div>

    <div class="form-group">
     <label for="items_introduction">商品説明</label>
     <div class="col-auto">
      <%= f.text_area :introduction ,class:"form-control"%>
     </div>
    </div>

    <div class="form-group">
     <label for="items_genre_id">ジャンル</label>
     <div class="col-auto">
      <%= f.text_field :genre,class:"form-control" %>
     </div>
    </div>

    <div class="form-group">
     <label for="items_price">税抜価格</label>
     <div class="col-auto">
      <%= f.number_field :price,class:"form-control" %>
     </div>
    </div>

    <div class="form-group">
     <label for="items_is_active">販売ステータス</label>
      <%= f.radio_button :is_active, true %>
      <%= f.label :is_active, "販売中" %>
      <%= f.radio_button :is_active, false %>
      <%= f.label :is_active, "販売停止中" %>
    </div>
    
    <div class="actions col-8">
    <%= f.submit '新規登録',class:"btn btn-sm btn-success" %>
    </div>
    <% end %>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class= "container">
 <h4>商品詳細</h4>
 <div class= "row">
  <div class="col-lg-4">
   <% if @item.image.present? %>
    <%= image_tag @item.image,size: '300x200' %>
   <% else %>
    <%= image_tag "no_image", size: '300x200'%>
   <% end %>
  </div>
  <div class="col-lg-8">
   <table class = "table table-borderless">
    <tbody>
     <tr>
     <td>商品名</td>
      <td><%= @item.name %></td>
     </tr>
     <tr>
      <td>商品説明</td>
      <td><%= @item.introduction %></td>
     </tr>
     <tr>
      <td>ジャンル</td>
      <td>
       <% @item.genres.each do |genre| %>
        <%= genre.name %>
       <% end %>
      </td>
     </tr>
     <tr>
      <td>税抜価格<br>（税込価格）</td>
      <td><%= @item.price.to_s + "円" %>  (<%= @item.get_tax_include_price.to_s + "円" %>)</td>
     </tr>
     <tr>
      <td>販売ステータス</td>
      <td>
       <% if @item.is_active %>
        <span class="text-success">販売中</span>
       <% else %>
        <span class="text-secondary">販売停止中</span>
       <% end %>
      </td>
     </tr>
    </tbody>
   </table>
   <%= link_to "編集する",edit_admin_item_path(@item.id),class:"btn btn-sm btn-success" %>
  </div>
 </div>
</div>