config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'admin' => 'homes#top'
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:index, :show, :update]
    resources :order_details, only:[:update]
    resources :genres, only:[:create, :index, :edit, :update]
    resources :items, only:[:new, :create, :index, :show, :edit, :update, :destroy]
  end

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    resources :addresses, only:[:create, :index, :edit, :update, :destroy]
    resources :orders, only:[:new, :create, :index, :show] do
      collection do
        post 'confirm'
      end
      member do
        get 'complete'
      end
    end
    resources :items, only:[:index, :show]
    resources :cart_items, only:[:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    resource :customers, only:[:show] do
      collection do
        get 'unsbscribe'
        patch 'withdraw'
      end
    end
  end

  devise_for :customers, skip:[:passwords], controllers:{
    registrations: "customers/registrations",
    sessions: "customers/sessions"
  }
  devise_for :admins, skip:[:registrations, :passwords], controllers:{
    sessions: "admins/sessions"
  }
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :cart_items, dependent: :destroy
  
  

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { wating_payment: 0, confirming: 1, producting: 2, preparation: 3, shipped: 4 }


  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::ApplicationController
  def index
    @orders = Order.where.not(status: nil).order(created_at: "DESC")
  end

  def show
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order.status = params[:order][:status]
    @order.save
    @order_details = OrderDetail.where(order_id: @order.id)
    if @order.status == "wating_payment"
      @order_details.each do |order_detail|
        order_detail.product_status = "wating_product"
        order_detail.save
      end
    end
    redirect_to admin_order_path(@order.id)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container mt-3">
  <div class="row justify-content-between mb-4">
      <div class="title col-md-auto px-auto">
        <p class="text-dark bg-light text-center">注文履歴一覧</p>
      </div>
  </div>
  <div class="row">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col" class="col-2">注文日時</th>
          <th scope="col" class="col-2">購入者</th>
          <th scope="col" class="col-2">個数</th>
          <th scope="col" class="col-2">注文ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @orders.each do |order| %>
        <tr>
          <th scope="row">
            <%= link_to admin_order_path(order.id) do %>
              <%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
            <% end %>
          </th>
          <td><%= order.name %></td>
          <td><%= OrderDetail.where(order_id: order.id).sum(:amount).to_s + "個" %></td>
          <td><%= order.status_i18n %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row pl-5">
    <div class="title col-md-auto bg-light text-dark mb-4">
      注文履歴詳細
    </div>
  </div>
  <div class="row">
    <div class="col-6">
      <p>注文情報</p>
      <table class="table table-bordered">
        <tbody>
          <tr>
            <td class="bg-light">注文日</td>
            <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
          </tr>
          <tr>
            <td class="bg-light">配送先</td>
            <td>
              <%= '〒' + @order.post_code + ' ' + @order.address + ' ' + @order.name %>
            </td>
          </tr>
          <tr>
            <td class="bg-light">支払方法</td>
            <td><%= @order.payment_method_i18n %></td>
          </tr>
          <tr>
            <td class="bg-light">ステータス</td>
            <td>
              <%= form_with model: @order, :url => {:action => :update} do |f| %>
                <%= f.select :status, [["入金待ち", "wating_payment"], ["入金確認中", "confirming"], ["製作中", "producting"], ["発送準備", "preparation"], ["発送済み", "shipped"]] %>
                <%= f.submit '更新する', class: "btn btn-success ml-2" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col-4 ml-5">
      <p>請求情報</p>
      <table class="table table-bordered">
        <tbody>
          <tr>
            <td class="bg-light">商品合計</td>
            <td><%= @order.total_price.to_s + "円" %></td>
          </tr>
          <tr>
            <td class="bg-light">配送料</td>
            <td><%= @order.postage.to_s + "円" %></td>
          </tr>
          <tr>
            <td class="bg-light">ご請求額</td>
            <td><%= (@order.total_price + @order.postage).to_s + "円" %></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
    <div class="row">
      <div class="col-10">
        <p>注文内容</p>
        <table class="table table-bordered mt-3">
          <thead class="bg-light">
            <th class="col-4">商品</th>
            <th class="col-2">単価(税込)</th>
            <th class="col-2">個数</th>
            <th class="col-2">小計</th>
            <th class="col-3">制作ステータス</th>
            <th class="col-1"></th>
          </thead>
          <% @order_details.each do |order_detail| %>
            <%= form_with model: order_detail, url: admin_order_detail_path(order_detail.id) do |f| %>
          <tbody>
              <tr>
                <td><%= order_detail.item.name %></td>
                <td><%= order_detail.item.get_tax_include_price.to_s + "円" %></td>
                <td><%= order_detail.amount.to_s + "個" %></td>
                <td><%= (order_detail.item.price * order_detail.amount).to_s + "円"%></td>
                  <td><%= f.select :product_status, [["制作不可", "cannot_product"], ["制作待ち", "wating_product"], ["製作中", "producting"], ["制作完了", "finish_product"]]  %></td>
                  <td><%= f.submit "更新する", class: "btn btn-success" %></td>
              </tr>
          </tbody>
            <% end %>
          <% end %>
        </table>
      </div>
  </div>

</div>