config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'admin' => 'homes#top'
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:index, :show, :update]
    resources :order_details, only:[:update]
    resources :genres, only:[:create, :index, :edit, :update]
    resources :items, only:[:new, :create, :index, :show, :edit, :update, :destroy]
  end

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    resources :addresses, only:[:create, :index, :edit, :update, :destroy]
    resources :orders, only:[:new, :create, :index, :show] do
      collection do
        post 'confirm'
      end
      member do
        get 'complete'
      end
    end
    resources :items, only:[:index, :show]
    resources :cart_items, only:[:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    resource :customers, only:[:show] do
      collection do
        get 'unsbscribe'
        patch 'withdraw'
      end
    end
  end

  devise_for :customers, skip:[:passwords], controllers:{
    registrations: "customers/registrations",
    sessions: "customers/sessions"
  }
  devise_for :admins, skip:[:registrations, :passwords], controllers:{
    sessions: "admins/sessions"
  }
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :genre_maps, dependent: :destroy, foreign_key: 'genre_id'
  has_many :items, through: :genre_maps
  
  validates :name, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < Admin::ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class = "container">
 <div class ="row">
  <div class="col-md-10">
   <h4>ジャンル編集</h4>
  </div>
   <%= form_with model:@genre, url: admin_genre_path(@genre.id), local:true do |f| %>
　 <div class = "row">
　  <label>ジャンル</label>
　  <%= f.text_field :name %>
　  <%= f.submit '変更を保存',class:"btn btn-sm btn-success" %>
　 </div>
　 <% end %>
 </div>
</div>

app/views/admin/genres/index.html.erb
<div class = "container">
 <div class ="row">
  <div class="col-md-10">
   <h4>ジャンル一覧・追加</h4>
  </div>
　
　<%= form_with model:@genre, url: admin_genres_path, local:true do |f| %>
　<div class = "row">
　 <label>ジャンル</label>
　 <%= f.text_field :name %>
　 <%= f.submit '新規登録',class:"btn btn-sm btn-success" %>
　</div>
　<% end %>

 <table class = "table">
  <thead>
   <tr>
    <th>ジャンル</th>
    <th></th>
   </tr>
  </thead>
  <tbody>
   <% @genres.each do |genre| %>
   <tr>
    <td><%= genre.name %></td>
    <td>
     <%= link_to '編集する', edit_admin_genre_path(genre.id), class: "btn btn-success" %>
    </td>
   </tr>
   <% end %>
  </tbody>
 </table>
 </div>
</div>