config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'admin' => 'homes#top'
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:index, :show, :update]
    resources :order_details, only:[:update]
    resources :genres, only:[:create, :index, :edit, :update]
    resources :items, only:[:new, :create, :index, :show, :edit, :update, :destroy]
  end

  scope module: :public do
    root to: 'homes#top'
    get 'about' => 'homes#about'
    resources :addresses, only:[:create, :index, :edit, :update, :destroy]
    resources :orders, only:[:new, :create, :index, :show] do
      collection do
        post 'confirm'
      end
      member do
        get 'complete'
      end
    end
    resources :items, only:[:index, :show]
    resources :cart_items, only:[:index, :create, :update, :destroy] do
      collection do
        delete 'destroy_all'
      end
    end
    resource :customers, only:[:show] do
      collection do
        get 'unsbscribe'
        patch 'withdraw'
      end
    end
  end

  devise_for :customers, skip:[:passwords], controllers:{
    registrations: "customers/registrations",
    sessions: "customers/sessions"
  }
  devise_for :admins, skip:[:registrations, :passwords], controllers:{
    sessions: "admins/sessions"
  }
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

   validates :address_code, presence: true
   validates :post_code, presence: true
   validates :name, presence: true

  def address_display
  '〒' + post_code + ' ' + address_code + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item

  validates :amount, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 20}
  def sum_of_price
    item.get_tax_include_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :post_code, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  
  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :genre_maps, dependent: :destroy, foreign_key: 'genre_id'
  has_many :items, through: :genre_maps
  
  validates :name, presence: true
end

app/models/genre_map.rb
class GenreMap < ApplicationRecord
   belongs_to :genre
   belongs_to :item
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :genre_maps, dependent: :destroy, foreign_key: 'item_id'
  has_many :genres, through: :genre_maps
  has_many :cart_items, dependent: :destroy
  has_many :order_details

  validates :name, presence: true
  validates :price, presence: true

  has_one_attached :image

  def save_genres(sent_genres)
    current_genres = self.genres.pluck(:name) unless self.genres.nil?
    old_genres = current_genres - sent_genres
    new_genres = sent_genres - current_genres

    old_genres.each do |old|
      self.genres.delete Genre.find_by(name: old)
    end

    new_genres.each do |new|
      new_genre_map = Genre.find_or_create_by(name: new)
      self.genres << new_genre_map
    end
  end


  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end

  def get_tax_include_price
    tax = 10
    add_tax = 1 + tax.to_f / 100
    (self.price.to_f * add_tax).round
  end

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :cart_items, dependent: :destroy
  
  

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { wating_payment: 0, confirming: 1, producting: 2, preparation: 3, shipped: 4 }


  
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum product_status: { cannot_product: 0, wating_product: 1, producting: 2, finish_product: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < Admin::ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::ApplicationController

  def new
    @item = Item.new
  end

  def index
    @items = Item.all
  end

  def create
    @item = Item.new(item_params)
    genre_list = params[:item][:genre].split(',')
    if @item.save
      @item.save_genres(genre_list)
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end

  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    genre_list = params[:item][:genre].split(',')
    if @item.update(item_params)
      @item.save_genres(genre_list)
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to admin_items_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :genre_id, :introduction, :price, :is_active, :image)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_up_path_for(resource)
    case resource
    when Admin
      admin_orders_path
    when Customer
      customers_path
    end
  end

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_orders_path
    when Customer
      root_path
    end
  end

  def after_sign_out_path_for(resource)
    case resource
    when :admin
      new_admin_session_path
    when :customer
      root_path
    end
  end

  

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :address, :post_code, :phone_number])
    devise_parameter_sanitizer.permit(:account_update, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :address, :post_code, :phone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
<% if customer_signed_in? %>

<li class="nav-item">
 <%= link_to destroy_customer_session_path, :method => :delete ,class:'text-light nav-link' do %>
  <i class ="fas fa-sign-out-alt"></i>Log out
 <% end %>
</li>

<% else %>

<li class="nav-item">
 <%= link_to new_customer_session_path,class:'text-light nav-link' do %>
  <i class ="fas fa-sign-in-alt"></i>Log in
 <% end %>
</li>
<% end %>

app/views/layouts/_heder.html.erb
<header class="navbar navbar navbar-dark bg-light navbar-inverse mb-5">
 <div class="container">
  <nav class='nav navbar-nav navbar-left' >
   <h2><a class="navbar-brand p-3 text-dark" href = "/" >NaganoCake</a></h2>
  </nav>
  <ul class="d-flex flex-row navbar-nav ml-auto">
  <% if customer_signed_in? %>

  <li class="nav-item m-4">
   ようこそ、<%= current_customer.last_name %>　さん！
  </li>

  <li class="nav-item m-3">
   <%= link_to "マイページ", customers_path, class: 'btn btn-outline-secondary' %>
  </li>

  <li class="nav-item m-3">
   <%= link_to "商品一覧", items_path, class: 'btn btn-outline-secondary' %>
  </li>

  <li class="nav-item m-3">
   <%= link_to "カート", cart_items_path, class: 'btn btn-outline-secondary' %>
  </li>

  <li class="nav-item m-3">
   <%= link_to "注文履歴", orders_path, class: 'btn btn-outline-secondary' %>
  </li>

  <li class="nav-item m-3">
   <%= link_to destroy_customer_session_path, :method => :delete ,class:'btn btn-outline-secondary' do %>
    <i class ="fas fa-sign-out-alt"></i>Log out
   <% end %>
  </li>

  <% elsif admin_signed_in? %>

  <li class="nav-item m-3">
   <%= link_to "商品一覧", admin_items_path, class: 'btn btn-outline-secondary' %>
  </li>

  <li class="nav-item m-3">
   <%= link_to "顧客一覧", admin_customers_path, class: 'btn btn-outline-secondary' %>
  </li>

  <li class="nav-item m-3">
   <%= link_to "注文履歴", admin_orders_path, class: 'btn btn-outline-secondary' %>
  </li>

   <li class="nav-item m-3">
   <%= link_to "ジャンル一覧", admin_genres_path, class: 'btn btn-outline-secondary' %>
  </li>

  <li class="nav-item m-3">
   <%= link_to destroy_admin_session_path, :method => :delete ,class:'btn btn-outline-secondary' do %>
    <i class ="fas fa-sign-out-alt"></i>Log out
   <% end %>
  </li>


  <% else %>

  <li class="nav-item m-3">
   <%= link_to "About", about_path, class: 'btn btn-outline-secondary' %>
  </li>

  <li class="nav-item m-3">
   <%= link_to "商品一覧", items_path, class: 'btn btn-outline-secondary' %>
  </li>

  <li class="nav-item m-3">
   <%= link_to "新規登録", new_customer_registration_path, class: 'btn btn-outline-secondary' %>
  </li>

  <li class="nav-item m-3">
   <%= link_to 'Log in', new_customer_session_path, class: "btn btn-outline-secondary" %>
  </li>
  <% end %>
  </ul>
   <div class="d-flex flex-row navbar-nav ml-auto">
  <input type="search" name="search" placeholder="search">
  <input type="submit" name="submit" value="検索">
  </div>
 </div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/heder" %>
    <main class="">
      <%= yield %>
    </main>
  </body>
</html>